name: Build and deploy infrastructure with CDK
on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #     - master
  # workflow_dispatch:
env:  
    AWS_REGION: ${{ vars.AWS_REGION  || 'eu-west-1' }}
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Verify repository structure
          run: |
            if [ ! -f "Infrastructure/cdk/src/InfrastructureStack.cs" ]; then
              echo "InfrastructureStack.cs not found in expected location"
              exit 1
            fi
        # - name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v1
        #   with:
        #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     aws-region: ${{ env.AWS_REGION }}

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
            aws-region: ${{ env.AWS_REGION }}               
        
        - name: Set up .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '10.0.x'
        
        - name: Set up NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '24.x'
            
        - name: Install CDK
          run: npm install -g aws-cdk

        - name: Check if NetworkStack exists
          id: check-network
          run: |
            if aws cloudformation describe-stacks \
                --stack-name NetworkStack \
                --region $AWS_REGION > /dev/null 2>&1; then
              echo "exists=true" >> $GITHUB_OUTPUT
            else
              echo "exists=false" >> $GITHUB_OUTPUT
            fi
            
        - name: Deploy NetworkStack if missing
          if: steps.check-network.outputs.exists == 'false'
          run: |
            cd Infrastructure
            dotnet restore cdk/src/Infrastructure.csproj
            cdk deploy NetworkStack --require-approval never --verbose
        
        - name: Deploy CDK stack
          run: |
            cd Infrastructure
            dotnet restore cdk/src/Infrastructure.csproj
            cdk deploy InfrastructureStack --require-approval never --verbose
