name: Sample standalone for testing org reusable

on:
  #workflow_call:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch:

env:
    AWS_REGION: ${{ vars.AWS_REGION  || 'eu-west-1' }}
    REPOSITORY_NAME: fargate-ecs-poc-dotnet-app-repo
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    CLUSTER_NAME: fargate-ecs-poc-cluster
    SERVICE_NAME: fargate-ecs-poc-dotnet-api-service
    DESIRED_COUNT: 2

jobs:
    run-tests:
        uses: torolos/github-workflows/.github/workflows/dotnet-test.yml@master
        with:
          test-project: ./apps/dotnetAPI.tests/dotnetAPI.tests.csproj
          verbosity: normal
          dotnet-version: '10.0.x'

    example-job:
        needs: run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Run shared common action
              uses: torolos/ci-cd/actions/test-action@master
              with:
                  verbosity: detailed
                  dotnet-version: 10.0.x
                  project-location: ./apps/dotnetAPI/dotnetAPI.csproj

    js-action-job:
        needs: run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Run js action
              uses: torolos/ci-cd/actions/js-action@master
              with:
                  test-project: "A test project"
                  message-count: 5
    
    deploy:
        needs: run-tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '10.0.x'

            - name: Build .NET API
              run: |
                echo "Building Docker image for .NET API..."
                dotnet build ./apps/dotnetAPI/dotnetAPI.csproj --configuration Release
