name: Build and Deploy to ECS Fargate

on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #     - master
  # workflow_dispatch:

env:
    AWS_REGION: ${{ vars.AWS_REGION  || 'eu-west-1' }}
    REPOSITORY_NAME: fargate-ecs-poc-node-app-repo
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    CLUSTER_NAME: fargate-ecs-poc-cluster
    SERVICE_NAME: fargate-ecs-poc-node-api-service
    DESIRED_COUNT: 1

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '24.x'
              
            - name: Run tests
              run: npx jest --verbose

    deploy:
        needs: run-tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Configure AWS credentials
            #   uses: aws-actions/configure-aws-credentials@v1
            #   with:
            #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #     aws-region: ${{ env.AWS_REGION }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
                aws-region: ${{ env.AWS_REGION }} 
            
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '24.x'

            - name: Build and push Node API Docker image
              run: |
                docker build -t ${{ env.REPOSITORY_NAME }} -f ./apps/nodeAPI/Dockerfile .
                docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest
                aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
                docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest

            - name: Deploy to ECS Fargate
              run: |
                aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --desired-count ${{ env.DESIRED_COUNT }} --force-new-deployment
