name: Deploy to AWS
on:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch:

env:  
    AWS_REGION: ${{ vars.AWS_REGION  || 'eu-west-1' }}

jobs:
  deploy-infrastructure:
    uses: ./.github/workflows/deploy-infrastructure.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    
  deploy-dotnet-api:
    needs: deploy-infrastructure
    uses: ./.github/workflows/deploy-dotnet-api.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy-node-api:
    needs: deploy-infrastructure
    uses: ./.github/workflows/deploy-node-api.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

